apiVersion: apps/v1
kind: Deployment
metadata:
##this is for the replicaset
 name: deployment
 labels: 
  name: replica-set
  project: roboshop
spec:
  replicas: 3
  selector:
    matchLabels:
      project: roboshop
  ##pod configuration
  template:
    metadata:
      name: pod-replica-set
      labels:
        project: roboshop
    spec:
      containers:
       - name: nginx
         image: nginx:latest

---
apiVersion: v1
kind: Service
metadata:
 ##Headless sevice is doesnt have the cluster ip
 name: headless-service
spec:
 selector:
   project: roboshop  
 ports:
   - protocol: TCP
     port: 80
     targetPort: 80 ##This is container port


---
apiVersion: v1
kind: Service
metadata:
 name: nginx-service
spec:
 clusterIp: None
 selector:
   project: roboshop  
 ports:
   - protocol: TCP
     port: 80
     targetPort: 80 ##This is container port