apiVersion: v1
Kind: Pod
metadata: 
 name: pod-configmap-demo
spec: 
  containers:
   - name: nginx-configmap
     image: nginx
     envFrom:
      - name: nginx-env
        configMapKeyRef:
          name: pod-config
