apiVersion: v1
Kind: Pod
metadata: 
 name: pod-configmap-demo
spec: 
  containers:
   - name: nginx-configmap
     image: nginx
     env:
      - name: nginx-env
        valueFrom:
          configMapKeyRef:
            name: configMap
            value: pod-config
